-- 财务单据智能风险审核系统 · 数据库初始化脚本（建表 + 索引 + 状态枚举）
-- 字段依据 PRD 12.1（与 schema/ 逐字段一致）；约束依据 PRD 12.2。
-- 方言 PostgreSQL：DECIMAL(18,2) 定点金额、TIMESTAMPTZ 带时区时间戳、JSONB 承载 *_json。
-- 可空性 PRD 未定义，故仅主键必填，其余列可空（与 schema/ 约定一致）。

-- 身份与权限
CREATE TABLE users (  -- 用户
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username TEXT, display_name TEXT,
    password_hash TEXT, status TEXT, created_at TIMESTAMPTZ, updated_at TIMESTAMPTZ
);
CREATE TABLE roles (  -- 角色
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, role_code TEXT, role_name TEXT, status TEXT,
    created_at TIMESTAMPTZ, updated_at TIMESTAMPTZ
);
CREATE TABLE permissions (  -- 权限点
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, permission_code TEXT, permission_name TEXT,
    resource_type TEXT, action_type TEXT
);
CREATE TABLE user_roles (  -- 用户-角色关联
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT, role_id BIGINT
);
CREATE TABLE role_permissions (  -- 角色-权限关联
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, role_id BIGINT, permission_id BIGINT
);
-- 审核会话
CREATE TABLE review_sessions (  -- 审核会话
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT,
    document_type TEXT CHECK (document_type IN ('对公付款单', '预付款单', '批量付款单', '费用报销单', '差旅报销单')),
    document_no TEXT, session_status TEXT, created_at TIMESTAMPTZ, updated_at TIMESTAMPTZ
);
CREATE TABLE session_messages (  -- 会话消息
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, session_id BIGINT, role TEXT, content TEXT,
    message_type TEXT, created_at TIMESTAMPTZ
);
CREATE TABLE session_slots (  -- 会话槽位状态
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, session_id BIGINT, slot_name TEXT,
    slot_value TEXT, is_confirmed BOOLEAN, updated_at TIMESTAMPTZ
);
-- 单据与明细
CREATE TABLE financial_documents (  -- 单据主表
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type TEXT CHECK (document_type IN ('对公付款单', '预付款单', '批量付款单', '费用报销单', '差旅报销单')),
    document_no TEXT,
    applicant_id BIGINT,
    applicant_department TEXT,
    budget_department TEXT,
    payee_name TEXT,
    payee_account TEXT,
    expense_category TEXT,
    amount DECIMAL(18,2),
    total_amount DECIMAL(18,2),
    currency TEXT,
    apply_date DATE,
    reason_text TEXT,
    contract_no TEXT,
    supplier_name TEXT,
    payment_ratio DECIMAL(18,2),
    payment_terms TEXT,
    planned_payment_date DATE,
    batch_total_amount DECIMAL(18,2),
    payment_count BIGINT,
    travel_destination TEXT,
    travel_start_date DATE,
    travel_end_date DATE,
    transport_fee DECIMAL(18,2),
    accommodation_fee DECIMAL(18,2),
    meal_fee DECIMAL(18,2),
    allowance DECIMAL(18,2),
    document_status TEXT CHECK (document_status IN (
        'draft', 'pending_review', 'reviewing', 'returned',
        'approved', 'rejected', 'withdrawn', 'voided')),
    current_version BIGINT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE TABLE document_versions (  -- 单据版本快照
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, document_id BIGINT, version_no BIGINT,
    document_snapshot_json JSONB, created_by BIGINT, created_at TIMESTAMPTZ
);
CREATE TABLE document_line_items (  -- 单据明细行
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT,
    item_type TEXT,
    item_name TEXT,
    expense_date DATE,
    expense_location TEXT,
    expense_account TEXT,
    quantity DECIMAL(18,2),
    unit_price DECIMAL(18,2),
    amount DECIMAL(18,2),
    payee_name TEXT,
    payee_account TEXT,
    payee_bank TEXT,
    planned_payment_date DATE,
    remark TEXT
);
CREATE TABLE document_attachments (  -- 附件
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT,
    document_version BIGINT,
    file_name TEXT,
    file_type TEXT,
    file_size BIGINT,
    file_path TEXT,
    file_hash TEXT,
    storage_status TEXT CHECK (storage_status IN ('uploading', 'stored', 'failed')),
    parse_status TEXT CHECK (parse_status IN ('pending', 'parsing', 'succeeded', 'failed', 'manual_review')),
    created_at TIMESTAMPTZ
);
CREATE TABLE attachment_parse_results (  -- 附件解析结果
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, attachment_id BIGINT, document_category TEXT,
    full_text TEXT, fields_json JSONB, evidence_positions_json JSONB, confidence REAL,
    created_at TIMESTAMPTZ
);
CREATE TABLE invoice_records (  -- 发票记录
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attachment_id BIGINT,
    invoice_code TEXT,
    invoice_no TEXT,
    seller_name TEXT,
    buyer_name TEXT,
    invoice_date DATE,
    amount_excluding_tax DECIMAL(18,2),
    tax_amount DECIMAL(18,2),
    amount_including_tax DECIMAL(18,2),
    currency TEXT
);
-- 审批
CREATE TABLE approval_workflows (  -- 审批流程定义
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, workflow_name TEXT,
    document_type TEXT CHECK (document_type IN ('对公付款单', '预付款单', '批量付款单', '费用报销单', '差旅报销单')),
    match_conditions_json JSONB, status TEXT, created_at TIMESTAMPTZ, updated_at TIMESTAMPTZ
);
CREATE TABLE approval_workflow_nodes (  -- 审批节点定义
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, workflow_id BIGINT, node_name TEXT,
    node_order BIGINT, approver_role TEXT, approval_mode TEXT, created_at TIMESTAMPTZ
);
CREATE TABLE approval_instances (  -- 审批实例
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, workflow_id BIGINT, document_id BIGINT,
    document_version BIGINT,
    instance_status TEXT CHECK (instance_status IN (
        'pending', 'running', 'approved', 'returned',
        'rejected', 'cancelled')),
    current_node_id BIGINT, started_at TIMESTAMPTZ, finished_at TIMESTAMPTZ
);
CREATE TABLE approval_tasks (  -- 审批任务
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, instance_id BIGINT, node_id BIGINT,
    approver_id BIGINT,
    task_status TEXT CHECK (task_status IN ('pending', 'approved', 'returned', 'rejected', 'cancelled')),
    review_comment TEXT, created_at TIMESTAMPTZ, processed_at TIMESTAMPTZ
);
CREATE TABLE document_status_logs (  -- 单据状态留痕
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, document_id BIGINT,
    from_status TEXT CHECK (from_status IN (
        'draft', 'pending_review', 'reviewing', 'returned', 'approved',
        'rejected', 'withdrawn', 'voided')),
    to_status TEXT CHECK (to_status IN (
        'draft', 'pending_review', 'reviewing', 'returned', 'approved',
        'rejected', 'withdrawn', 'voided')),
    operator_id BIGINT, remark TEXT, created_at TIMESTAMPTZ
);
-- 分析与报告
CREATE TABLE analysis_tasks (  -- 分析任务
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, session_id BIGINT, document_id BIGINT,
    task_status TEXT CHECK (task_status IN (
        'queued', 'querying_document', 'loading_attachments',
        'parsing_attachments', 'analyzing', 'succeeded', 'failed', 'cancelled')),
    current_step TEXT, started_at TIMESTAMPTZ, finished_at TIMESTAMPTZ, error_message TEXT
);
CREATE TABLE risk_findings (  -- 风险项
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT,
    risk_type TEXT,
    risk_level TEXT CHECK (risk_level IN ('low', 'medium', 'high')),
    risk_title TEXT,
    description TEXT,
    actual_value_json JSONB,
    reference_value_json JSONB,
    threshold_json JSONB,
    evidence_json JSONB,
    suggestion_text TEXT,
    review_status TEXT CHECK (review_status IN ('pending', 'confirmed', 'dismissed')),
    created_at TIMESTAMPTZ
);
CREATE TABLE review_reports (  -- 风险审核报告
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT,
    document_id BIGINT,
    overall_risk_level TEXT CHECK (overall_risk_level IN ('low', 'medium', 'high')),
    risk_summary_json JSONB,
    amount_comparison_json JSONB,
    recommendation TEXT CHECK (recommendation IN ('建议通过', '补充材料', '人工复核', '建议驳回')),
    report_markdown TEXT,
    created_at TIMESTAMPTZ
);
CREATE TABLE manual_reviews (  -- 人工复核记录
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, report_id BIGINT, reviewer_id BIGINT,
    review_result TEXT, review_comment TEXT, reviewed_at TIMESTAMPTZ
);
-- 规则与费用标准
CREATE TABLE review_rules (  -- 审核规则
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_code TEXT,
    rule_name TEXT,
    rule_type TEXT,
    params_json JSONB,
    status TEXT,
    effective_date DATE,
    updated_by BIGINT,
    updated_at TIMESTAMPTZ
);
CREATE TABLE expense_standards (  -- 费用标准
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, expense_category TEXT, department TEXT,
    job_level TEXT, region TEXT, standard_amount DECIMAL(18,2), currency TEXT, effective_date DATE
);
-- 参考数据与审计
CREATE TABLE market_price_references (  -- 市场价参考
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name TEXT,
    specification TEXT,
    region TEXT,
    price_min DECIMAL(18,2),
    price_max DECIMAL(18,2),
    currency TEXT,
    source_name TEXT,
    effective_date DATE
);
CREATE TABLE supplier_profiles (  -- 供应商档案
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, supplier_code TEXT, supplier_name TEXT,
    credit_status TEXT, blacklist_status TEXT, risk_tags_json JSONB, bank_accounts_json JSONB,
    updated_at TIMESTAMPTZ
);
CREATE TABLE audit_logs (  -- 操作审计日志
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT, action_type TEXT,
    resource_type TEXT, resource_id BIGINT, detail_json JSONB, created_at TIMESTAMPTZ
);

-- 索引与唯一约束（PRD 12.2）
CREATE UNIQUE INDEX ux_financial_documents_document_no ON financial_documents (document_no);  -- 单据编号全局唯一
CREATE INDEX ix_review_sessions_user_status ON review_sessions (user_id, session_status);
CREATE INDEX ix_financial_documents_type_status ON financial_documents (document_type, document_status);
CREATE INDEX ix_financial_documents_applicant ON financial_documents (applicant_id);
CREATE INDEX ix_financial_documents_apply_date ON financial_documents (apply_date);
CREATE INDEX ix_approval_tasks_approver_status ON approval_tasks (approver_id, task_status);
CREATE INDEX ix_risk_findings_task_level ON risk_findings (task_id, risk_level);
